name: build-and-deploy

on:
  schedule:
    - cron: '30 05 * * 1-5'   # 07:30 Madrid verano
    - cron: '30 06 * * 1-5'   # 07:30 Madrid invierno
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install deps
        run: npm install

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Generate report (OpenAI + Investing)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
