name: build-and-deploy

on:
  schedule:
    - cron: '30 05 * * 1-5'   # 07:30 Madrid en verano (CEST)
    - cron: '30 06 * * 1-5'   # 07:30 Madrid en invierno (CET)
  workflow_dispatch: {}       # permitir ejecutar a mano

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      # ⬇️ Arreglo: instalar deps sin package-lock.json
      - name: Install deps
        run: npm install

      - name: Build site
        run: npm run build

      # ⬇️ Solo valida hora cuando viene del cron
      - name: Validar 07:30 Madrid
        if: ${{ github.event_name == 'schedule' }}
        run: |
          node -e "const d=new Date().toLocaleString('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',hour12:false}); if(d!=='07:30'){console.log('No es 07:30 Madrid, salgo. Hora local:', d); process.exit(78);} else {console.log('Es 07:30 Madrid, publico.');}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
